version: '3'
services:
  db:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - .:/airbnb/

  web:
    image: aldocodes/airbnb-host-module:latest
    command: "npm start"
    links: 
      - db:db
    ports:
      - 3000:3000
    depends_on:
      - db
    environment:
      - MONGO_URI=mongodb://localhost/airbnb

  proxyServer:
    image: aldocodes/host-proxy-server:latest
    ports:
      - 3001:3001
