const seeds = 
[
  {
    "name": "Marth",
    "location": "Los Angeles, California, United States",
    "join_date": "Joined in March 2011",
    "reviews": "568 Reviews",
    "references": "3 References",
    "description": "Born and raised from the Kingdom of Altea, and now living in Santa Monica with my sword and beautiful home. Happy to have the opportunity to share my home with people from around the world!",
    "languages": "English",
    "response_rate": "97%",
    "response_time": "within a few hours",
    "picture": "https://vignette.wikia.nocookie.net/fireemblem/images/4/45/Marth_Fates_Portrait.png/revision/latest?cb=20161015042604",
    "superHost": true,
    "verified": true,
    "listing_id": 1,
    "map": "don\"t forget to use a map",
    "locationDescription": "Real Santa Monica is one of the best places where you can be, in Los Angeles. It is beautiful, nice, and kingdomy."
  },{
    "name": "Mario",
    "location": "Los Angeles, California, United States",
    "join_date": "Joined in March 2012",
    "reviews": "200 Reviews",
    "references": "2 References",
    "description": "Born and raised from Mushroom Kingdom, and now living in Los Angeles with my wife Peach and our pet Yoshi, who will leaving us soon. Happy to have the opportunity to share our homes with people from around the world!",
    "languages": "Italian, English",
    "response_rate": "93%",
    "response_time": "within an hour",
    "picture": "https://files.gamebanana.com/img/ss/srends/530-90_59bc49fd521ee.jpg",
    "superHost": true,
    "verified": true,
    "listing_id": 2,
    "map": "don\"t forget to use a map",
    "locationDescription": "Oh yeah, Petite Private Cottage is located in the safest area in Los Angeles. Beautiful, wonderful, and peaceful."
  },{
    "name": "Link",
    "location": "Los Angeles, California, United States",
    "join_date": "Joined in March 2005",
    "reviews": "702 Reviews",
    "references": "4 References",
    "description": "Born and raised outside of Hyrule Temple, and now living in Venice Beach with Zelda and our son Young Link. We are happy to have the opportunity to share our homes with people from around the world!",
    "languages": "Elvish, English",
    "response_rate": "87%",
    "response_time": "within a few minutes",
    "picture": "https://www.ssbwiki.com/images/thumb/3/32/Link_SSB4.png/250px-Link_SSB4.png",
    "superHost": true,
    "verified": true,
    "listing_id": 3,
    "map": "don\"t forget to use a map",
    "locationDescription": "Venice Beach is located in the most beautiful beach you can ever find in Los Angeles. It is an amazing and exciting beach. There are numerous restaurants, bars, and people here!"
  },{
    "name": "Pikachu",
    "location": "San Francisco, California, United States",
    "join_date": "Joined in March 2014",
    "reviews": "50 Reviews",
    "references": "2 References",
    "description": "Born and raised in a lab from Pallet Town, and now living in Garden Suite in San Francisco. Happy to have the opportunity to share my park with people from around the world!",
    "languages": "Pokemanian",
    "response_rate": "89%",
    "response_time": "within a few hours",
    "picture": "https://www.ssbwiki.com/images/thumb/a/a0/Pikachu_SSB4.png/250px-Pikachu_SSB4.png",
    "superHost": true,
    "verified": true,
    "listing_id": 4,
    "map": "don\"t forget to use a map",
    "locationDescription": "Garden Suite is located in the Mission District and is an amazingly vibrant and exciting neighborhood. There are numerous restaurants, bars, and music options within two blocks of the house. This is a central location that offers quick access to the surrounding areas."
  },{
    "name": "Yoshi",
    "location": "San Francisco, California, United States",
    "join_date": "Joined in March 2012",
    "reviews": "345 Reviews",
    "references": "3 References",
    "description": "Born and raised from Yoshi Island, left Mario and family to have my own place. Happy to have the opportunity to share my home with people from around the world!",
    "languages": "Yoshinian",
    "response_rate": "40%",
    "response_time": "within a few hours",
    "picture": "https://www.ssbwiki.com/images/thumb/2/29/Yoshi_SSB4.png/250px-Yoshi_SSB4.png",
    "superHost": true,
    "verified": true,
    "listing_id": 5 ,
    "map": "don\"t forget to use a map",
    "locationDescription": "The neighborhood is a diverse and mixed use area. Western SOMA is considered a popular place for live-work environments and is the home to a lot of technology start-ups. There is access to public transportation, rental cars, buses, taxis, and bikes."
  },
  {
    "name": "Wario",
    "location": "Portland, Oregon, United States",
    "join_date": "Joined in March 2016",
    "reviews": "145 Reviews",
    "references": "1 References",
    "description": "Born and raised from Mushroom Kingdom, left the gangsta's life and now living in Portland with the love of my life, my motorcycle.",
    "languages": "English",
    "response_rate": "10%",
    "response_time": "within a few hours",
    "picture": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRzHHEr8rWIbKjdcY91Ism9Tqngc9EUic63F3i2nICPhXilQoAO",
    "superHost": true,
    "verified": true,
    "listing_id": 6,
    "map": "don\"t forget to use a map",
    "locationDescription": "This efficiency studio is located in close-in SE Portland near tons of bars and restaurants. It's on the ground floor of a modern architecture townhouse offering the perfect location for exploring all things Portland! Sleep soundly in the hand-crafted queen murphy bed and walk to everything you need! Fully equipped kitchen and bathroom offers every convenience & the private patio is perfect for spring and summer days. The ductless heating and air-conditioner keeps you comfortable year-round!"
  },
  {
    "name": "Rosalina",
    "location": "Seattle, WA, United States",
    "join_date": "Joined in March 2014",
    "reviews": "545 Reviews",
    "references": "2 References",
    "description": "Born and raised from Gateway Galaxy, decided to move to Earth and settled in Seattle in a cozy private loft apt. Happy to have the opportunity to share my apt with anyone, preferably a star.",
    "languages": "English",
    "response_rate": "90%",
    "response_time": "within a few hours",
    "picture": "https://www.mariowiki.com/images/thumb/6/6c/Rosalina_Artwork_-_Super_Mario_3D_World.png/200px-Rosalina_Artwork_-_Super_Mario_3D_World.png",
    "superHost": true,
    "verified": true,
    "listing_id": 7,
    "map": "don\"t forget to use a map",
    "locationDescription":  "Enjoy being at the heart of South Lake Union in downtown Seattle, just steps from two Starbucks and several easy lunch spots, as well as a Tom Douglas restaurant and a fun sports bar. Explore further with the streetcar, just steps away."
  },
  {
    "name": "Donkey Kong",
    "location": "Seattle, WA, United States",
    "join_date": "Joined in March 2012",
    "reviews": "545 Reviews",
    "references": "2 References",
    "description": "Born and raised in a jungle, and now living in a New Capitol Hill Studio in Seattle. Happy to rent my place to anyone who is a banana lover.",
    "languages": "English",
    "response_rate": "30%",
    "response_time": "within a few hours",
    "picture": "https://www.mariowiki.com/images/thumb/c/cb/Donkey_Kong_Artwork_%28alt%29_-_Donkey_Kong_Country_Tropical_Freeze.png/300px-Donkey_Kong_Artwork_%28alt%29_-_Donkey_Kong_Country_Tropical_Freeze.png",
    "superHost": true,
    "verified": true,
    "listing_id": 8 ,
    "map": "don\"t forget to use a map",
    "locationDescription": "Capitol Hill is known as the hip and vibrant neighborhood in Seattle. You will bunch of nice restaurants, bars, and coffee shop especially around Pike and Pine St."
  },
  {
    "name": "Peach",
    "location": "Seattle, United States",
    "join_date": "Joined in March 2013",
    "reviews": "500 Reviews",
    "references": "7 References",
    "description": "Born and raised in Mushroom Kingdom. I am a princess who left the kingdom because my husband wanted me to get away from whom he thought was my kidnapper. Truth is, just like hiding my relationship with Bowser from my husband, I do own a property in Seattle which has a free private room. It is cozy, beautiful, and warm!",
    "languages": "English",
    "response_rate": "80%",
    "response_time": "within a few hours",
    "picture": "https://pbs.twimg.com/profile_images/875781452163686400/RJ_erUsX_400x400.jpg",
    "superHost": true,
    "verified": true,
    "listing_id": 9,
    "map": "don\"t forget to use a map",
    "locationDescription": "I'm in Beacon Hill, an area conveniently located between SeaTac International Airport and downtown Seattle. CenturyLink Field is less than 10 minutes away by car, if you're here for a concert or game."
  },
  {
    "name": "Browser",
    "location": "San Diego, CA, United States",
    "join_date": "Joined in March 2011",
    "reviews": "329 Reviews",
    "references": "5 References",
    "description": "Living in San Diego looking for Peach. In the meantime, check out this luxury downtown Getaway.",
    "languages": "English",
    "response_rate": "20%",
    "response_time": "within a few hours",
    "picture": "https://boygeniusreport.files.wordpress.com/2015/05/bowser_sm3dl.png?w=782",
    "superHost": true,
    "verified": true,
    "listing_id": 10,
    "map": "don\"t forget to use a map",
    "locationDescription": "Located in one of the most amazing areas of San Diego- To your West you are 6 blocks from The San Diego Bay, 3 blocks to the Village of Little Italy, To the East you are 6 blocks from the World Famous Balboa Park and Zoo. To the South you are 15 minutes from the Energetic Night Life of the Gaslamp District"
  },
  {
    "name": "Wal Luigi",
    "location": "Las Vegas, NV, United States",
    "join_date": "Joined in March 2016",
    "reviews": "144 Reviews",
    "references": "4 References",
    "description": "All the way from Mushroom Kingdom, now living in Las Vegas in Hitech City. Got a spare room for anyone who loves to gamble and drink. Just 9 minutes away from the Strip.",
    "languages": "English",
    "response_rate": "30%",
    "response_time": "within a few hours",
    "picture": "http://images1.tickld.com/live/avatars/Waluigi_1546_avatar_20150323231235_e0c4e0aa65856031235ac6965ec14e4d.png",
    "superHost": true,
    "verified": true,
    "listing_id": 11 ,
    "map": "don\"t forget to use a map",
    "locationDescription": "Wal Luigi's Place is conveniently located near the strip (1.5 miles) and allows you to avoid the congestion to and from the airport. It's perfect for those looking for more chill surrounds while still being only a short Uber/taxi ride away from the strip. There is an Einstein Bros bagels and Starbucks within walking distance along with multiple inexpensive locally owned food options. There's a Go Kart Racing facility across the street called Pole Position Raceway."
  },
  {
    "name": "King Dedede",
    "location": "Phoenix, AZ, United States",
    "join_date": "Joined in March 2016",
    "reviews": "700 Reviews",
    "references": "3 References",
    "description": "Living Phoenix Arizona, looking for anyone who is cool enough to share a space with the King himself.",
    "languages": "English",
    "response_rate": "40%",
    "response_time": "within a few hours",
    "picture": "https://vignette.wikia.nocookie.net/deathbattlefanon/images/4/4d/Kingdedede.png/revision/latest?cb=20140809054519",
    "superHost": true,
    "verified": true,
    "listing_id": 12 ,
    "map": "don\"t forget to use a map",
    "locationDescription": "King Dedede's home is located in Phoenix, Arizona, United States. There is a city bus stop located just across the street from my space and also Grid bicycle rentals on the North West corner of 5th ave."
  },
  {
    "name": "Toad",
    "location": "Bangkok, Thailand",
    "join_date": "Joined in March 2011",
    "reviews": "800 Reviews",
    "references": "2 References",
    "description": "Born and raised in Mushroom Kingdom. Now living in Bangkok Thailand where everything is greener and humid. Renting out the beautiful Bohemian Pool House to anyone who wants to have fun!",
    "languages": "English, Toadian",
    "response_rate": "90%",
    "response_time": "within a few hours",
    "picture": "https://vignette.wikia.nocookie.net/scratchpad/images/1/19/Toad.jpg/revision/latest?cb=20121202001316",
    "superHost": true,
    "verified": true,
    "listing_id": 13 ,
    "map": "don\"t forget to use a map",
    "locationDescription": "Toad’s home is located in Bangkok, Krung Thep Maha Nakhon, Thailand. Within 5-10 min walk you have the following places: Emporium Shopping Mall, BTS Prompong, Emquartier Shopping Mall, Hilton, Benjasiri Park, Japanese restaurants, Sky Bar, Multiple restaurants, Starbucks"
  },
  {
    "name": "Kirby",
    "location": "Yokohama, Japan",
    "join_date": "Joined in March 2010",
    "reviews": "1001 Reviews",
    "references": "5 References",
    "description": "Born and raised in Dream Land, migrated to Yokohama Japan and bought a beautiful property near Pacifico. Looking for anyone who wants to play with me!",
    "languages": "English, Japanese",
    "response_rate": "90%",
    "response_time": "within a few hours",
    "picture": "https://upload.wikimedia.org/wikipedia/en/thumb/5/5c/Kirby.png/220px-Kirby.png",
    "superHost": true,
    "verified": true,
    "listing_id": 14,
    "map": "don\"t forget to use a map",
    "locationDescription": "My house is very close to Chinatown, Yokohama Chinatown is concentrated in the Chinese restaurant-based shops, of which 12 stores have been more than half a century history. Yokohama Chinatown tourists, 95% are not Chinese, in the world of Chinatown is quite rare. Yokohama also has a number of Western-style buildings, typical representatives include Japan's most famous Baroque architecture one of the Kanagawa Prefectural Historical Museum. Yamashita Park is part of the revival of the Kanto Earthquake and has now become one of Japan's most famous metropolitan parks"
  },
  {
    "name": "Jon Snow",
    "location": "Jeddan, Saudi Arabia",
    "join_date": "Joined in March 2011",
    "reviews": "340 Reviews",
    "references": "2 References",
    "description": "Born and raised in Winterfell, now living in Saudi Arabia, away from the snow. Happy to have the opportunity to share my suite with anyone!",
    "languages": "English",
    "response_rate": "50%",
    "response_time": "within a few hours",
    "picture": "https://pbs.twimg.com/profile_images/901947348699545601/hqRMHITj_400x400.jpg",
    "superHost": true,
    "verified": true,
    "listing_id": 15,
    "map": "don\"t forget to use a map",
    "locationDescription": "Jon Snow's home is located in Jeddah, Makkah Province, Saudi Arabia."
  },
  {
    "name": "Daenerys Targaryen",
    "location": "Pune, India",
    "join_date": "Joined in March 2011",
    "reviews": "580 Reviews",
    "references": "5 References",
    "description": "Tired of the Iron Throne, I retire myself in Pune India. Now living in Green Garden room, I welcome anyone who wants to rent the space. Don't worry, my dragons won't bite you, if you behave yourself.",
    "languages": "English",
    "response_rate": "100%",
    "response_time": "within a few minutes",
    "picture": "https://i.ytimg.com/vi/WtXo__olwu8/maxresdefault.jpg",
    "superHost": true,
    "verified": true,
    "listing_id": 16,
    "map": "don\"t forget to use a map",
    "locationDescription": "Daenerys Targaryen’s home is located in Pune, India."
  },
  {
    "name": "Tyrian Lannister",
    "location": "Delhi, India",
    "join_date": "Joined in March 2012",
    "reviews": "510 Reviews",
    "references": "2 References",
    "description": "Followed Daenerys all the way to India, I now live by myself in a luxury house all to myself. Feeling lonely, renting out a luxury room for anyone who wants to keep me accompany.",
    "languages": "English",
    "response_rate": "98%",
    "response_time": "within a few minutes",
    "picture": "https://img.resized.co/buzz_ie/eyJkYXRhIjoie1widXJsXCI6XCJodHRwOlxcXC9cXFwvczMtZXUtd2VzdC0xLmFtYXpvbmF3cy5jb21cXFwvc3RvcmFnZS5wdWJsaXNoZXJwbHVzLmllXFxcL21lZGlhLmJ1enouaWVcXFwvdXBsb2Fkc1xcXC8yMDE3XFxcLzA0XFxcL3R5cmlvbi1sYW5uaXN0ZXItbGF1Z2hpbmctZ2FtZS1vZi10aHJvbmVzLS0xMDI0eDUzOS5wbmdcIixcIndpZHRoXCI6NzAwLFwiaGVpZ2h0XCI6MzcwLFwiZGVmYXVsdFwiOlwiaHR0cHM6XFxcL1xcXC93d3cuYnV6ei5pZVxcXC9pXFxcL25vLWltYWdlLnBuZ1wifSIsImhhc2giOiI4MTk0MGJiYThmZWFkNWVhZmUxZmNkMzNiYzk3NzYwYjc1NWE4NWQyIn0=/tyrion-lannister-laughing-game-of-thrones-1024x539.png",
    "superHost": true,
    "verified": true,
    "listing_id": 17,
    "map": "don\"t forget to use a map",
    "locationDescription": "Tyrian's home is located in New Delhi, Delhi, India. Affluent neighbourhood with plenty of parks. The 400-acre Hauz Khas forest is a 5-min walk away. Extremely safe with 24-hr guard patrols. Small market within 2 mins walking distance for all essentials - groceries, milk, medicines, dry clean service, ATM, phone recharge. You're 2 mins away from the neighbourhood health club where you can use the gym/swimming pool/massage facilities/spa"
  },
  {
    "name": "Bronn",
    "location": "Casablanca, Morocco",
    "join_date": "Joined in March 2014",
    "reviews": "280 Reviews",
    "references": "3 References",
    "description": "Away from the war of the Iron Throne, I am now living in Morocco in a beautiful colorful house. One beautiful blue bedroom is available for anyone who wants to share the space with me.",
    "languages": "English",
    "response_rate": "70%",
    "response_time": "within a few hours",
    "picture": "https://www.hbo.com/content/dam/hbodata/series/game-of-thrones/character/s5/bronn-1920.jpg/_jcr_content/renditions/cq5dam.web.1200.675.jpeg",
    "superHost": true,
    "verified": true,
    "listing_id": 18,
    "map": "don\"t forget to use a map",
    "locationDescription": "The neighborhood is very peaceful in spite of being close to the city centre. In 3 minutes you are at a big supermarket, and you are in walking distance to good restaurants and the best coffee shops and patisserie in Casablanca. (We even have a Starbucks!)"
  },
  {
    "name": "Joffrey",
    "location": "Shanghai, China",
    "join_date": "Joined in March 2012",
    "reviews": "3 Reviews",
    "references": "2 References",
    "description": "They think I am dead. Well well, surprise, I am well and alive. Recovering for years in a hospital in China, I now decided to stay and bought myself a beautiful place. Renting a loft with 2 beds with beautiful view Jing'an.",
    "languages": "English",
    "response_rate": "10%",
    "response_time": "within a few hours",
    "picture": "https://vignette.wikia.nocookie.net/gameofthrones/images/4/4d/Purple_Wedding.png/revision/latest?cb=20150210223603",
    "superHost": true,
    "verified": true,
    "listing_id": 19,
    "map": "don\"t forget to use a map",
    "locationDescription": "The neighborhood is at the centre of Shanghai's Former French Concession & in walking distance from 4 subway lines(Line 1, 7, 9 & 10). Also, it is located near the Hengshan Road bars & pubs, popular cafes & restaurants, cinemas, visitor attractions."
  },
  {
    "name": "Iggrid",
    "location": "Lahore, Pakistan",
    "join_date": "Joined in March 2014",
    "reviews": "194 Reviews",
    "references": "5 References",
    "description": "I was once declared dead. But the Lord of Light resurrected me and one day I woke up in Pakistan. Don't know how to go back to my home with the Wildlings. But I like it here and bought myself an apartment to myself. Anyways, anyone wants to share the space with me, here's your opportunity!",
    "languages": "English",
    "response_rate": "80%",
    "response_time": "within a few minutes",
    "picture": "https://vignette.wikia.nocookie.net/gameofthrones/images/2/28/Ygritte-promotionals4pic.jpg/revision/latest?cb=20170107042949",
    "superHost": true,
    "verified": true,
    "listing_id": 20,
    "map": "don\"t forget to use a map",
    "locationDescription": "Iggrid’s home is located in Lahore, Punjab, Pakistan."
  },
  {
    "name": "Theon Greyjoy",
    "location": "Rio de Janeiro, Brazil",
    "join_date": "Joined in March 2015",
    "reviews": "90 Reviews",
    "references": "2 References",
    "description": "My name is Theon, Theon Greyjoy. I'm renting out an awesome getaway spot in Ipanema for those who wants to relax here in Rio de Janeiro, Brazil",
    "languages": "English",
    "response_rate": "40%",
    "response_time": "within a few hours",
    "picture": "https://cdn-images-1.medium.com/max/1600/1*-gDptk0nn2dGpMCx3K9Ftw.jpeg",
    "superHost": true,
    "verified": true,
    "listing_id": 21,
    "map": "don\"t forget to use a map",
    "locationDescription": "This is the best spot in Rio. Everything happens here. All big events are just 1 min. to walk away. Any kind of parade or concert (like the Stones) will either be on the beach in front of Copacabana Palace Hotel or on Avenida Atlantica. It's definitely the most lively area in all of Rio. - The apt is very spacious. Everyone adores the huge balcony (on second floor) which allows you to see the action below. There are no cars passing. It's a pedestrian street, and you will see Brazilians socializing, having a churrasco, playing a guitar, dancing etc. - The subway station Cardeal Arco Verde and all major bus lines are a short walk away, so it's extremely easy to move around. Most people stay put, though, since you're at the best spot anyway!"
  },
  {
    "name": "Samuell Tarly",
    "location": "Mexico City, Mexico",
    "join_date": "Joined in March 2013",
    "reviews": "230 Reviews",
    "references": "4 References",
    "description": "Coming all the way down here by myself to Mexico City to study their new modern medicines. Looking for anyone who is willing to be my assistant in this Roomy Apartment near Downtown.",
    "languages": "English",
    "response_rate": "90%",
    "response_time": "within a few minutes",
    "picture": "http://www.wetpaint.com/wp-content/uploads/2017/03/game-of-thrones-samwell-tarly-750x522-1489000496.jpg",
    "superHost": true,
    "verified": true,
    "listing_id": 22,
    "map": "don\"t forget to use a map",
    "locationDescription": "The La condesa neighborhood is a trendy, safe and green area of the city. Bikes routes, walking roads, as well as two parks are available around, with lots of great restaurants and places to enjoy the nightlife. The area is secure, going out and walking home is safe even during the night."
  },
  {
    "name": "Hodor",
    "location": "Shanghai, China",
    "join_date": "Joined in March 2013",
    "reviews": "300 Reviews",
    "references": "3 References",
    "description": "Although all I can say is Hodor. What I meant to say is that I will hold the door for anyone who wants to adventure themselves in a European Style Apartment close to Disneyland here in Shanghai, China.",
    "languages": "Hodor",
    "response_rate": "98%",
    "response_time": "within a few minutes",
    "picture": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/avatars/70/7035ffad65de2bc1c0d08c24aaf9bb57f7130be6_full.jpg",
    "superHost": true,
    "verified": true,
    "listing_id": 23,
    "map": "don\"t forget to use a map",
    "locationDescription": "The neighborhood is at the centre of Shanghai's Former French Concession & in walking distance from 4 subway lines(Line 1, 7, 9 & 10). Also, it is located near the Hengshan Road bars & pubs, popular cafes & restaurants, cinemas, visitor attractions."
  },
  {
    "name": "Sansa Stark",
    "location": "Madrid, Spain",
    "join_date": "Joined in March 2013",
    "reviews": "500 Reviews",
    "references": "2 References",
    "description": "Having to go through a bunch of horrible experiences, I decided to move myself to Madrid in Spain. Living in a modern flat in Metro Lucero, I welcome anyone who wants share the space with me. Preferably a girl.",
    "languages": "English",
    "response_rate": "98%",
    "response_time": "within a few minutes",
    "picture": "https://pbs.twimg.com/profile_images/567089182615830528/F2H311Ev_400x400.jpeg",
    "superHost": true,
    "verified": true,
    "listing_id": 24,
    "map": "don\"t forget to use a map",
    "locationDescription": "If you want to enjoy the most genuine and authentic Madrid City Heart, while being hosted in a very quiet and silent apartment in one the most typical districts of the whole city, and at the same time discovering the most multicultural, bohemian and alternative neighborhood in Madrid, just a few minutes walking from all the main highlights and touristics spots of the city, my apartment at Lavapiés is the perfect place for you. My apartment will be the perfect place for you to enjoy a romantic scape with your partner, a fantastic stay with a friend and also a great family gateway to discover the beauty and magic of Madrid!!"
  },
  {
    "name": "Tywin Lannister",
    "location": "Johannesburg, South Africa",
    "join_date": "Joined in March 2012",
    "reviews": "576 Reviews",
    "references": "2 References",
    "description": "They thought that I was dead. Well well, my son has failed to kill me. I faked my own death in hope of the Lannister step up their game and take over the Iron Throne. I migrated myself in South Africa and renting properties. Welcome to the perfect spot with views of the Jozi sunset.",
    "languages": "English",
    "response_rate": "70%",
    "response_time": "within a few minutes",
    "picture": "https://www.themarysue.com/wp-content/uploads/2014/09/tywin.jpg",
    "superHost": true,
    "verified": true,
    "listing_id": 25,
    "map": "don\"t forget to use a map",
    "locationDescription": "Tywin Lannister's palace is in Johannesburg, South Africa"
  },
  {
    "name": "Annalise Valdez",
    "location": "Schenzhen, China",
    "join_date": "Joined in March 2012",
    "reviews": "578 Reviews",
    "references": "2 References",
    "description": "Born and raised in China, a real estate agent. I have the opportunity to welcome anyone to this beautiful house with a balcony and city view.",
    "languages": "Chinese, English",
    "response_rate": "70%",
    "response_time": "within a few minutes",
    "picture": "https://s3-media3.fl.yelpcdn.com/bphoto/aQIAfFc8pK7rN47LA8w8tg/ls.jpg",
    "superHost": true,
    "verified": true,
    "listing_id": 26,
    "map": "don\"t forget to use a map",
    "locationDescription": "Annalise's home is located in Schenzhen, China"
  },
  {
    "name": "Itzel Blanchard",
    "location": "Bogota, Colombia",
    "join_date": "Joined in March 2011",
    "reviews": "600 Reviews",
    "references": "3 References",
    "description": "Born and raised in Bogota, Colombia, and now honored to have the opportunity to share my home with people from around the world!",
    "languages": "English, Spanish",
    "response_rate": "97%",
    "response_time": "within a few hours",
    "picture": "https://i.pinimg.com/236x/52/c4/e9/52c4e9e859d7f55cb83c65d10c1560e6--noroc-cali-colombia.jpg",
    "superHost": true,
    "verified": true,
    "listing_id": 27,
    "map": "don\"t forget to use a map",
    "locationDescription": "Itzel Blanchard's home is located in Bogota, Colombia."
  },
  {
    "name": "Julie Gray",
    "location": "Rio de Janeiro, Brazil",
    "join_date": "Joined in March 2007",
    "reviews": "903 Reviews",
    "references": "4 References",
    "description": "The name is Gray, Julie Gray. Two dogs. Animal lovers. Design lover. Which brings me the opportunity to share a brand nw house with amazing views and location to anyone who appreciates beauty!",
    "languages": "English, Spanish",
    "response_rate": "97%",
    "response_time": "within a few hours",
    "picture": "http://members.openbooktoronto.com/sites/default/files/obt/illustrations/profile%20pic.jpg",
    "superHost": true,
    "verified": true,
    "listing_id": 28,
    "map": "don\"t forget to use a map",
    "locationDescription": "Julie's home is located in Rio de Janeiro, Brazil."
  },
  {
    "name": "Cohen Lowe",
    "location": "Jakarta, Indonesia",
    "join_date": "Joined in March 2011",
    "reviews": "589 Reviews",
    "references": "2 References",
    "description": "Born and raised in Los Angeles, now living in Jakarta Indonesia. I have the opportunity to rent one of my modern and comfy flat with super location to anyone who wants to have a relaxing time!",
    "languages": "English, Indonesian",
    "response_rate": "68%",
    "response_time": "within a few hours",
    "picture": "http://media.bizj.us/view/img/9924932/orthocarolina-dr-bruce-cohen*750xx1500-2000-0-84.jpg",
    "superHost": true,
    "verified": true,
    "listing_id": 29,
    "map": "don\"t forget to use a map",
    "locationDescription": "Where I live is located near Pakuwon Indah. It is a walking distance to the mall and its near all the best restaurants in Jakarta."
  },
  {
    "name": "Dominique Burns",
    "location": "Surabaya, Indonesia",
    "join_date": "Joined in March 2010",
    "reviews": "590 Reviews",
    "references": "2 References",
    "description": "Living in Surabaya Indonesia, I am renting a beautiful clean and spacious room to anyone who wants to share the house with me. It is near the mall.",
    "languages": "English, Indonesian",
    "response_rate": "70%",
    "response_time": "within a few hours",
    "picture": "https://m.media-amazon.com/images/M/MV5BZmZkNTYzYjgtOTQyZS00MjRiLTlmZmItOTcyMTg0YmUwODRjXkEyXkFqcGdeQXVyMjIzOTc2ODk@._V1_UX214_CR0,0,214,317_AL_.jpg",
    "superHost": true,
    "verified": true,
    "listing_id": 30,
    "map": "don\"t forget to use a map",
    "locationDescription": "Darmo Harpan is located in the beautiful side of Surabaya. It is a walking distance to a Sinar Mall."
  },
  {
    "name": "Jovany Ford",
    "location": "Seoul, South Korea",
    "join_date": "Joined in March 2011",
    "reviews": "538 Reviews",
    "references": "2 References",
    "description": "Living in Seoul, South Korea, I love to take a walk. So glad to be able to use this opportunity to rent this house to those who wants to be my walking pair.",
    "languages": "English, Korean",
    "response_rate": "49%",
    "response_time": "within a few hours",
    "picture": "https://amp.businessinsider.com/images/5ad4c8f4146e7122008b49f1-750-563.jpg",
    "superHost": true,
    "verified": true,
    "listing_id": 31,
    "map": "don\"t forget to use a map",
    "locationDescription": "Jovany's home is located in Seoul, South Korea."
  },
  {
    "name": "Harper Hendrix",
    "location": "Seoul, South Korea",
    "join_date": "Joined in March 2012",
    "reviews": "500 Reviews",
    "references": "2 References",
    "description": "Living with a wife in this cute delightful fillhouse. Well it is at the heart of Seoul, the neighbourhood is peaceful that you won't be bothered by noises. It will be our pleasure if you find the same warmth as you feel at home.",
    "languages": "English, Korean",
    "response_rate": "90%",
    "response_time": "within a few hours",
    "picture": "https://images.summitmedia-digital.com/preview/images/articles/2016/04/15/korean/nm_korean.jpg",
    "superHost": true,
    "verified": true,
    "listing_id": 32,
    "map": "don\"t forget to use a map",
    "locationDescription": "Harper's home is located in Seoul, South Korea."
  },
  {
    "name": "Armani York",
    "location": "Seoul, South Korea",
    "join_date": "Joined in March 2011",
    "reviews": "430 Reviews",
    "references": "2 References",
    "description": "Born and raised in Italy, a realtor, a husband and a father of two sons. I am honored to be renting one of the properties in Seoul, South Korea.",
    "languages": "English, Korean",
    "response_rate": "90%",
    "response_time": "within a few hours",
    "picture": "http://www.italoamericano.org/sites/default/files/styles/crop_show/public/ricc.jpg?itok=po1TeEgQ",
    "superHost": true,
    "verified": true,
    "listing_id": 33,
    "map": "don\"t forget to use a map",
    "locationDescription": "Jovany lives in Seoul, South Korea."
  },
  {
    "name": "Marth",
    "location": "London, United Kingdom",
    "join_date": "Joined in March 2011",
    "reviews": "568 Reviews",
    "references": "3 References",
    "description": "Born and raised from the Kingdom of Altea, and now living in the United Kingdom with my sword and beautiful home. Happy to have the opportunity to share my home with people from around the world!",
    "languages": "English",
    "response_rate": "97%",
    "response_time": "within a few hours",
    "picture": "https://vignette.wikia.nocookie.net/fireemblem/images/4/45/Marth_Fates_Portrait.png/revision/latest?cb=20161015042604",
    "superHost": true,
    "verified": true,
    "listing_id": 34,
    "map": "don\"t forget to use a map",
    "locationDescription": "Real Santa Monica is one of the best places where you can be, in London. It is beautiful, nice, and kingdomy."
  },{
    "name": "Mario",
    "location": "London, United Kingdom",
    "join_date": "Joined in March 2012",
    "reviews": "200 Reviews",
    "references": "2 References",
    "description": "Born and raised from Mushroom Kingdom, and now living in the United Kingdom with my wife Peach and our pet Yoshi, who will leaving us soon. Happy to have the opportunity to share our homes with people from around the world!",
    "languages": "Italian, English",
    "response_rate": "93%",
    "response_time": "within an hour",
    "picture": "https://files.gamebanana.com/img/ss/srends/530-90_59bc49fd521ee.jpg",
    "superHost": true,
    "verified": true,
    "listing_id": 35,
    "map": "don\"t forget to use a map",
    "locationDescription": "Oh yeah, Petite Private Cottage is located in the safest area in London. Beautiful, wonderful, and peaceful."
  },{
    "name": "Link",
    "location": "London, United Kingdom",
    "join_date": "Joined in March 2005",
    "reviews": "702 Reviews",
    "references": "4 References",
    "description": "Born and raised outside of Hyrule Temple, and now living in the United Kingdom with Zelda and our son Young Link. We are happy to have the opportunity to share our homes with people from around the world!",
    "languages": "Elvish, English",
    "response_rate": "87%",
    "response_time": "within a few minutes",
    "picture": "https://www.ssbwiki.com/images/thumb/3/32/Link_SSB4.png/250px-Link_SSB4.png",
    "superHost": true,
    "verified": true,
    "listing_id": 36,
    "map": "don\"t forget to use a map",
    "locationDescription": "Venice Beach is located in the most beautiful beach you can ever find in London. It is an amazing and exciting beach. There are numerous restaurants, bars, and people here!"
  },{
    "name": "Pikachu",
    "location": "Taipei City, Republic of China (Taiwan)",
    "join_date": "Joined in March 2014",
    "reviews": "50 Reviews",
    "references": "2 References",
    "description": "Born and raised in a lab from Pallet Town, and now living in Garden Suite in China. Happy to have the opportunity to share my park with people from around the world!",
    "languages": "Pokemanian",
    "response_rate": "89%",
    "response_time": "within a few hours",
    "picture": "https://www.ssbwiki.com/images/thumb/a/a0/Pikachu_SSB4.png/250px-Pikachu_SSB4.png",
    "superHost": true,
    "verified": true,
    "listing_id": 37,
    "map": "don\"t forget to use a map",
    "locationDescription": "Garden Suite is located in the Mission District and is an amazingly vibrant and exciting neighborhood. There are numerous restaurants, bars, and music options within two blocks of the house. This is a central location that offers quick access to the surrounding areas."
  },{
    "name": "Yoshi",
    "location": "Taipei City, Republic of China (Taiwan)",
    "join_date": "Joined in March 2012",
    "reviews": "345 Reviews",
    "references": "3 References",
    "description": "Born and raised from Yoshi Island, left Mario and family to have my own place. Happy to have the opportunity to share my home with people from around the world!",
    "languages": "Yoshinian",
    "response_rate": "40%",
    "response_time": "within a few hours",
    "picture": "https://www.ssbwiki.com/images/thumb/2/29/Yoshi_SSB4.png/250px-Yoshi_SSB4.png",
    "superHost": true,
    "verified": true,
    "listing_id": 38,
    "map": "don\"t forget to use a map",
    "locationDescription": "The neighborhood is a diverse and mixed use area. Western SOMA is considered a popular place for live-work environments and is the home to a lot of technology start-ups. There is access to public transportation, rental cars, buses, taxis, and bikes."
  },
  {
    "name": "Wario",
    "location": "Taipei City, Republic of China (Taiwan)",
    "join_date": "Joined in March 2016",
    "reviews": "145 Reviews",
    "references": "1 References",
    "description": "Born and raised from Mushroom Kingdom, left the gangsta's life and now living in Portland with the love of my life, my motorcycle.",
    "languages": "English",
    "response_rate": "10%",
    "response_time": "within a few hours",
    "picture": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRzHHEr8rWIbKjdcY91Ism9Tqngc9EUic63F3i2nICPhXilQoAO",
    "superHost": true,
    "verified": true,
    "listing_id": 39,
    "map": "don\"t forget to use a map",
    "locationDescription": "This efficiency studio is located in close-in SE Portland near tons of bars and restaurants. It's on the ground floor of a modern architecture townhouse offering the perfect location for exploring all things Portland! Sleep soundly in the hand-crafted queen murphy bed and walk to everything you need! Fully equipped kitchen and bathroom offers every convenience & the private patio is perfect for spring and summer days. The ductless heating and air-conditioner keeps you comfortable year-round!"
  },
  {
    "name": "Rosalina",
    "location": "Berlin, Germany",
    "join_date": "Joined in March 2014",
    "reviews": "545 Reviews",
    "references": "2 References",
    "description": "Born and raised from Gateway Galaxy, decided to move to Earth and settled in Germany in a cozy private loft apt. Happy to have the opportunity to share my apt with anyone, preferably a star.",
    "languages": "English",
    "response_rate": "90%",
    "response_time": "within a few hours",
    "picture": "https://www.mariowiki.com/images/thumb/6/6c/Rosalina_Artwork_-_Super_Mario_3D_World.png/200px-Rosalina_Artwork_-_Super_Mario_3D_World.png",
    "superHost": true,
    "verified": true,
    "listing_id": 40,
    "map": "don\"t forget to use a map",
    "locationDescription":  "Enjoy being at the heart of South Lake Union in downtown Berlin, just steps from two Starbucks and several easy lunch spots, as well as a Tom Douglas restaurant and a fun sports bar. Explore further with the streetcar, just steps away."
  },
  {
    "name": "Donkey Kong",
    "location": "Berlin, Germany",
    "join_date": "Joined in March 2012",
    "reviews": "545 Reviews",
    "references": "2 References",
    "description": "Born and raised in a jungle, and now living in a New Capitol Hill Studio in Germany. Happy to rent my place to anyone who is a banana lover.",
    "languages": "English",
    "response_rate": "30%",
    "response_time": "within a few hours",
    "picture": "https://www.mariowiki.com/images/thumb/c/cb/Donkey_Kong_Artwork_%28alt%29_-_Donkey_Kong_Country_Tropical_Freeze.png/300px-Donkey_Kong_Artwork_%28alt%29_-_Donkey_Kong_Country_Tropical_Freeze.png",
    "superHost": true,
    "verified": true,
    "listing_id": 41,
    "map": "don\"t forget to use a map",
    "locationDescription": "Capitol Hill is known as the hip and vibrant neighborhood in Berlin. You will bunch of nice restaurants, bars, and coffee shop especially around Pike and Pine St."
  },
  {
    "name": "Peach",
    "location": "Berlin, Germany",
    "join_date": "Joined in March 2013",
    "reviews": "500 Reviews",
    "references": "7 References",
    "description": "Born and raised in Mushroom Kingdom. I am a princess who left the kingdom because my husband wanted me to get away from whom he thought was my kidnapper. Truth is, just like hiding my relationship with Bowser from my husband, I do own a property in Berlin, Germany which has a free private room. It is cozy, beautiful, and warm!",
    "languages": "English",
    "response_rate": "80%",
    "response_time": "within a few hours",
    "picture": "https://pbs.twimg.com/profile_images/875781452163686400/RJ_erUsX_400x400.jpg",
    "superHost": true,
    "verified": true,
    "listing_id": 42,
    "map": "don\"t forget to use a map",
    "locationDescription": "I'm in Beacon Hill, an area conveniently located between SeaTac International Airport and downtown Seattle. CenturyLink Field is less than 10 minutes away by car, if you're here for a concert or game."
  },
  {
    "name": "Browser",
    "location": "Chicago, IL",
    "join_date": "Joined in March 2011",
    "reviews": "329 Reviews",
    "references": "5 References",
    "description": "Living in San Diego looking for Peach. In the meantime, check out this luxury downtown Getaway.",
    "languages": "English",
    "response_rate": "20%",
    "response_time": "within a few hours",
    "picture": "https://boygeniusreport.files.wordpress.com/2015/05/bowser_sm3dl.png?w=782",
    "superHost": true,
    "verified": true,
    "listing_id": 43,
    "map": "don\"t forget to use a map",
    "locationDescription": "Located in one of the most amazing areas of Chicago- To your West you are 6 blocks from The San Diego Bay, 3 blocks to the Village of Little Italy, To the East you are 6 blocks from the World Famous Balboa Park and Zoo. To the South you are 15 minutes from the Energetic Night Life of the Gaslamp District"
  },
  {
    "name": "Wal Luigi",
    "location": "Chicago, IL",
    "join_date": "Joined in March 2016",
    "reviews": "144 Reviews",
    "references": "4 References",
    "description": "All the way from Mushroom Kingdom, now living in Las Vegas in Hitech City. Got a spare room for anyone who loves to gamble and drink. Just 9 minutes away from the Strip.",
    "languages": "English",
    "response_rate": "30%",
    "response_time": "within a few hours",
    "picture": "http://images1.tickld.com/live/avatars/Waluigi_1546_avatar_20150323231235_e0c4e0aa65856031235ac6965ec14e4d.png",
    "superHost": true,
    "verified": true,
    "listing_id": 44,
    "map": "don\"t forget to use a map",
    "locationDescription": "Wal Luigi's Place is conveniently located near the strip (1.5 miles) and allows you to avoid the congestion to and from the airport. It's perfect for those looking for more chill surrounds while still being only a short Uber/taxi ride away from the strip. There is an Einstein Bros bagels and Starbucks within walking distance along with multiple inexpensive locally owned food options. There's a Go Kart Racing facility across the street called Pole Position Raceway."
  },
  {
    "name": "King Dedede",
    "location": "San Jose, CA",
    "join_date": "Joined in March 2016",
    "reviews": "700 Reviews",
    "references": "3 References",
    "description": "Living Phoenix Arizona, looking for anyone who is cool enough to share a space with the King himself.",
    "languages": "English",
    "response_rate": "40%",
    "response_time": "within a few hours",
    "picture": "https://vignette.wikia.nocookie.net/deathbattlefanon/images/4/4d/Kingdedede.png/revision/latest?cb=20140809054519",
    "superHost": true,
    "verified": true,
    "listing_id": 45,
    "map": "don\"t forget to use a map",
    "locationDescription": "King Dedede's home is located in San Jose, CA, United States. There is a city bus stop located just across the street from my space and also Grid bicycle rentals on the North West corner of 5th ave."
  },
  {
    "name": "Toad",
    "location": "San Jose, CA",
    "join_date": "Joined in March 2011",
    "reviews": "800 Reviews",
    "references": "2 References",
    "description": "Born and raised in Mushroom Kingdom. Now living in Bangkok Thailand where everything is greener and humid. Renting out the beautiful Bohemian Pool House to anyone who wants to have fun!",
    "languages": "English, Toadian",
    "response_rate": "90%",
    "response_time": "within a few hours",
    "picture": "https://vignette.wikia.nocookie.net/scratchpad/images/1/19/Toad.jpg/revision/latest?cb=20121202001316",
    "superHost": true,
    "verified": true,
    "listing_id": 46,
    "map": "don\"t forget to use a map",
    "locationDescription": "Toad’s home is located in Bangkok, Krung Thep Maha Nakhon, Thailand. Within 5-10 min walk you have the following places: Emporium Shopping Mall, BTS Prompong, Emquartier Shopping Mall, Hilton, Benjasiri Park, Japanese restaurants, Sky Bar, Multiple restaurants, Starbucks"
  },
  {
    "name": "Kirby",
    "location": "Newark, NJ",
    "join_date": "Joined in March 2010",
    "reviews": "1001 Reviews",
    "references": "5 References",
    "description": "Born and raised in Dream Land, migrated to New Jersey and bought a beautiful property near Pacifico. Looking for anyone who wants to play with me!",
    "languages": "English, Japanese",
    "response_rate": "90%",
    "response_time": "within a few hours",
    "picture": "https://upload.wikimedia.org/wikipedia/en/thumb/5/5c/Kirby.png/220px-Kirby.png",
    "superHost": true,
    "verified": true,
    "listing_id": 47,
    "map": "don\"t forget to use a map",
    "locationDescription": "My house is very close to Chinatown, Yokohama Chinatown is concentrated in the Chinese restaurant-based shops, of which 12 stores have been more than half a century history. Yokohama Chinatown tourists, 95% are not Chinese, in the world of Chinatown is quite rare. Yokohama also has a number of Western-style buildings, typical representatives include Japan's most famous Baroque architecture one of the Kanagawa Prefectural Historical Museum. Yamashita Park is part of the revival of the Kanto Earthquake and has now become one of Japan's most famous metropolitan parks"
  },
  {
    "name": "Jon Snow",
    "location": "Newark, NJ",
    "join_date": "Joined in March 2011",
    "reviews": "340 Reviews",
    "references": "2 References",
    "description": "Born and raised in Winterfell, now living in Saudi Arabia, away from the snow. Happy to have the opportunity to share my suite with anyone!",
    "languages": "English",
    "response_rate": "50%",
    "response_time": "within a few hours",
    "picture": "https://pbs.twimg.com/profile_images/901947348699545601/hqRMHITj_400x400.jpg",
    "superHost": true,
    "verified": true,
    "listing_id": 48,
    "map": "don\"t forget to use a map",
    "locationDescription": "Jon Snow's home is located in Newark New Jersey."
  },
  {
    "name": "Daenerys Targaryen",
    "location": "Singapore, Singapore",
    "join_date": "Joined in March 2011",
    "reviews": "580 Reviews",
    "references": "5 References",
    "description": "Tired of the Iron Throne, I retire myself in Pune India. Now living in Green Garden room, I welcome anyone who wants to rent the space. Don't worry, my dragons won't bite you, if you behave yourself.",
    "languages": "English",
    "response_rate": "100%",
    "response_time": "within a few minutes",
    "picture": "https://i.ytimg.com/vi/WtXo__olwu8/maxresdefault.jpg",
    "superHost": true,
    "verified": true,
    "listing_id": 49,
    "map": "don\"t forget to use a map",
    "locationDescription": "Daenerys Targaryen’s home is located in Singapore."
  },
  {
    "name": "Tyrian Lannister",
    "location": "Singapore, Singapore",
    "join_date": "Joined in March 2012",
    "reviews": "510 Reviews",
    "references": "2 References",
    "description": "Followed Daenerys all the way to India, I now live by myself in a luxury house all to myself. Feeling lonely, renting out a luxury room for anyone who wants to keep me accompany.",
    "languages": "English",
    "response_rate": "98%",
    "response_time": "within a few minutes",
    "picture": "https://img.resized.co/buzz_ie/eyJkYXRhIjoie1widXJsXCI6XCJodHRwOlxcXC9cXFwvczMtZXUtd2VzdC0xLmFtYXpvbmF3cy5jb21cXFwvc3RvcmFnZS5wdWJsaXNoZXJwbHVzLmllXFxcL21lZGlhLmJ1enouaWVcXFwvdXBsb2Fkc1xcXC8yMDE3XFxcLzA0XFxcL3R5cmlvbi1sYW5uaXN0ZXItbGF1Z2hpbmctZ2FtZS1vZi10aHJvbmVzLS0xMDI0eDUzOS5wbmdcIixcIndpZHRoXCI6NzAwLFwiaGVpZ2h0XCI6MzcwLFwiZGVmYXVsdFwiOlwiaHR0cHM6XFxcL1xcXC93d3cuYnV6ei5pZVxcXC9pXFxcL25vLWltYWdlLnBuZ1wifSIsImhhc2giOiI4MTk0MGJiYThmZWFkNWVhZmUxZmNkMzNiYzk3NzYwYjc1NWE4NWQyIn0=/tyrion-lannister-laughing-game-of-thrones-1024x539.png",
    "superHost": true,
    "verified": true,
    "listing_id": 50,
    "map": "don\"t forget to use a map",
    "locationDescription": "Tyrian's home is located in New Delhi, Delhi, India. Affluent neighbourhood with plenty of parks. The 400-acre Hauz Khas forest is a 5-min walk away. Extremely safe with 24-hr guard patrols. Small market within 2 mins walking distance for all essentials - groceries, milk, medicines, dry clean service, ATM, phone recharge. You're 2 mins away from the neighbourhood health club where you can use the gym/swimming pool/massage facilities/spa"
  },
  {
    "name": "Bronn",
    "location": "Singapore, Singapore",
    "join_date": "Joined in March 2014",
    "reviews": "280 Reviews",
    "references": "3 References",
    "description": "Away from the war of the Iron Throne, I am now living in Singapore in a beautiful colorful house. One beautiful blue bedroom is available for anyone who wants to share the space with me.",
    "languages": "English",
    "response_rate": "70%",
    "response_time": "within a few hours",
    "picture": "https://www.hbo.com/content/dam/hbodata/series/game-of-thrones/character/s5/bronn-1920.jpg/_jcr_content/renditions/cq5dam.web.1200.675.jpeg",
    "superHost": true,
    "verified": true,
    "listing_id": 51,
    "map": "don\"t forget to use a map",
    "locationDescription": "The neighborhood is very peaceful in spite of being close to the city centre. In 3 minutes you are at a big supermarket, and you are in walking distance to good restaurants and the best coffee shops and patisserie in Casablanca. (We even have a Starbucks!)"
  },
  {
    "name": "Joffrey",
    "location": "Beijing, China, China",
    "join_date": "Joined in March 2012",
    "reviews": "3 Reviews",
    "references": "2 References",
    "description": "They think I am dead. Well well, surprise, I am well and alive. Recovering for years in a hospital in China, I now decided to stay and bought myself a beautiful place. Renting a loft with 2 beds with beautiful view Jing'an.",
    "languages": "English",
    "response_rate": "10%",
    "response_time": "within a few hours",
    "picture": "https://vignette.wikia.nocookie.net/gameofthrones/images/4/4d/Purple_Wedding.png/revision/latest?cb=20150210223603",
    "superHost": true,
    "verified": true,
    "listing_id": 52,
    "map": "don\"t forget to use a map",
    "locationDescription": "The neighborhood is at the centre of Beijing's Former French Concession & in walking distance from 4 subway lines(Line 1, 7, 9 & 10). Also, it is located near the Hengshan Road bars & pubs, popular cafes & restaurants, cinemas, visitor attractions."
  },
  {
    "name": "Iggrid",
    "location": "Beijing, China",
    "join_date": "Joined in March 2014",
    "reviews": "194 Reviews",
    "references": "5 References",
    "description": "I was once declared dead. But the Lord of Light resurrected me and one day I woke up in China. Don't know how to go back to my home with the Wildlings. But I like it here and bought myself an apartment to myself. Anyways, anyone wants to share the space with me, here's your opportunity!",
    "languages": "English",
    "response_rate": "80%",
    "response_time": "within a few minutes",
    "picture": "https://vignette.wikia.nocookie.net/gameofthrones/images/2/28/Ygritte-promotionals4pic.jpg/revision/latest?cb=20170107042949",
    "superHost": true,
    "verified": true,
    "listing_id": 53,
    "map": "don\"t forget to use a map",
    "locationDescription": "Iggrid’s home is located in Beijing, China."
  },
  {
    "name": "Theon Greyjoy",
    "location": "Beijing, China",
    "join_date": "Joined in March 2015",
    "reviews": "90 Reviews",
    "references": "2 References",
    "description": "My name is Theon, Theon Greyjoy. I'm renting out an awesome getaway spot in Beijing for those who wants to relax here in China",
    "languages": "English",
    "response_rate": "40%",
    "response_time": "within a few hours",
    "picture": "https://cdn-images-1.medium.com/max/1600/1*-gDptk0nn2dGpMCx3K9Ftw.jpeg",
    "superHost": true,
    "verified": true,
    "listing_id": 54,
    "map": "don\"t forget to use a map",
    "locationDescription": "This is the best spot in Beijing. Everything happens here. All big events are just 1 min. to walk away. Any kind of parade or concert (like the Stones) will either be on the beach in front of Copacabana Palace Hotel or on Avenida Atlantica. It's definitely the most lively area in all of Rio. - The apt is very spacious. Everyone adores the huge balcony (on second floor) which allows you to see the action below. There are no cars passing. It's a pedestrian street, and you will see Brazilians socializing, having a churrasco, playing a guitar, dancing etc. - The subway station Cardeal Arco Verde and all major bus lines are a short walk away, so it's extremely easy to move around. Most people stay put, though, since you're at the best spot anyway!"
  },
  {
    "name": "Samuell Tarly",
    "location": "Guangzhou, China",
    "join_date": "Joined in March 2013",
    "reviews": "230 Reviews",
    "references": "4 References",
    "description": "Coming all the way down here by myself to Guangzhou China to study their new modern medicines. Looking for anyone who is willing to be my assistant in this Roomy Apartment near Downtown.",
    "languages": "English",
    "response_rate": "90%",
    "response_time": "within a few minutes",
    "picture": "http://www.wetpaint.com/wp-content/uploads/2017/03/game-of-thrones-samwell-tarly-750x522-1489000496.jpg",
    "superHost": true,
    "verified": true,
    "listing_id": 55,
    "map": "don\"t forget to use a map",
    "locationDescription": "The Guangzhou neighborhood is a trendy, safe and green area of the city. Bikes routes, walking roads, as well as two parks are available around, with lots of great restaurants and places to enjoy the nightlife. The area is secure, going out and walking home is safe even during the night."
  },
  {
    "name": "Hodor",
    "location": "Guangzhou, China",
    "join_date": "Joined in March 2013",
    "reviews": "300 Reviews",
    "references": "3 References",
    "description": "Although all I can say is Hodor. What I meant to say is that I will hold the door for anyone who wants to adventure themselves in a European Style Apartment close to Disneyland here in Guangzhou, China.",
    "languages": "Hodor",
    "response_rate": "98%",
    "response_time": "within a few minutes",
    "picture": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/avatars/70/7035ffad65de2bc1c0d08c24aaf9bb57f7130be6_full.jpg",
    "superHost": true,
    "verified": true,
    "listing_id": 56,
    "map": "don\"t forget to use a map",
    "locationDescription": "The neighborhood is at the centre of Guangzhou's Former French Concession & in walking distance from 4 subway lines(Line 1, 7, 9 & 10). Also, it is located near the Hengshan Road bars & pubs, popular cafes & restaurants, cinemas, visitor attractions."
  },
  {
    "name": "Sansa Stark",
    "location": "Guangzhou, China",
    "join_date": "Joined in March 2013",
    "reviews": "500 Reviews",
    "references": "2 References",
    "description": "Having to go through a bunch of horrible experiences, I decided to move myself to China. Living in a modern flat in Metro Sanji, I welcome anyone who wants share the space with me. Preferably a girl.",
    "languages": "English",
    "response_rate": "98%",
    "response_time": "within a few minutes",
    "picture": "https://pbs.twimg.com/profile_images/567089182615830528/F2H311Ev_400x400.jpeg",
    "superHost": true,
    "verified": true,
    "listing_id": 57,
    "map": "don\"t forget to use a map",
    "locationDescription": "If you want to enjoy the most genuine and authentic Guangzhou Heart, while being hosted in a very quiet and silent apartment in one the most typical districts of the whole city, and at the same time discovering the most multicultural, bohemian and alternative neighborhood in Guangzhou, just a few minutes walking from all the main highlights and touristics spots of the city, my apartment at Lavapiés is the perfect place for you. My apartment will be the perfect place for you to enjoy a romantic scape with your partner, a fantastic stay with a friend and also a great family gateway to discover the beauty and magic of Guangzhou!!"
  },
  {
    "name": "Tywin Lannister",
    "location": "Moscow, Russia",
    "join_date": "Joined in March 2012",
    "reviews": "576 Reviews",
    "references": "2 References",
    "description": "They thought that I was dead. Well well, my son has failed to kill me. I faked my own death in hope of the Lannister step up their game and take over the Iron Throne. I migrated myself in Russia and renting properties. Welcome to the perfect spot with views of the Moscow sunset.",
    "languages": "English",
    "response_rate": "70%",
    "response_time": "within a few minutes",
    "picture": "https://www.themarysue.com/wp-content/uploads/2014/09/tywin.jpg",
    "superHost": true,
    "verified": true,
    "listing_id": 58,
    "map": "don\"t forget to use a map",
    "locationDescription": "Tywin Lannister's palace is in Moscow, Russia"
  },
  {
    "name": "Annalise Valdez",
    "location": "Moscow, Russia",
    "join_date": "Joined in March 2012",
    "reviews": "578 Reviews",
    "references": "2 References",
    "description": "Born and raised in Russia, a real estate agent. I have the opportunity to welcome anyone to this beautiful house with a balcony and city view.",
    "languages": "Russian, English",
    "response_rate": "70%",
    "response_time": "within a few minutes",
    "picture": "https://s3-media3.fl.yelpcdn.com/bphoto/aQIAfFc8pK7rN47LA8w8tg/ls.jpg",
    "superHost": true,
    "verified": true,
    "listing_id": 59,
    "map": "don\"t forget to use a map",
    "locationDescription": "Annalise's home is located in Schenzhen, China"
  },
  {
    "name": "Itzel Blanchard",
    "location": "Moscow, Russia",
    "join_date": "Joined in March 2011",
    "reviews": "600 Reviews",
    "references": "3 References",
    "description": "Born and raised in Moscow, Russia and now honored to have the opportunity to share my home with people from around the world!",
    "languages": "English, Russian",
    "response_rate": "97%",
    "response_time": "within a few hours",
    "picture": "https://i.pinimg.com/236x/52/c4/e9/52c4e9e859d7f55cb83c65d10c1560e6--noroc-cali-colombia.jpg",
    "superHost": true,
    "verified": true,
    "listing_id": 60,
    "map": "don\"t forget to use a map",
    "locationDescription": "Itzel Blanchard's home is located in Moscow, Russia."
  },
  {
    "name": "Julie Gray",
    "location": "Cape Town, South Africa",
    "join_date": "Joined in March 2007",
    "reviews": "903 Reviews",
    "references": "4 References",
    "description": "The name is Gray, Julie Gray. Two dogs. Animal lovers. Design lover. Which brings me the opportunity to share a brand nw house with amazing views and location to anyone who appreciates beauty!",
    "languages": "Afrikaans, English, Tsonga, Tswana, Venda, ",
    "response_rate": "97%",
    "response_time": "within a few hours",
    "picture": "http://members.openbooktoronto.com/sites/default/files/obt/illustrations/profile%20pic.jpg",
    "superHost": true,
    "verified": true,
    "listing_id": 61,
    "map": "don\"t forget to use a map",
    "locationDescription": "Julie Gray's home is located in Cape Town, South Africa."
  },
  {
    "name": "Cohen Lowe",
    "location": "Cape Town, South Africa",
    "join_date": "Joined in March 2011",
    "reviews": "589 Reviews",
    "references": "2 References",
    "description": "Born and raised in Los Angeles, now living in South Africa. I have the opportunity to rent one of my modern and comfy flat with super location to anyone who wants to have a relaxing time!",
    "languages": "Afrikaans, English, SiSwati, and, Zulu",
    "response_rate": "68%",
    "response_time": "within a few hours",
    "picture": "http://media.bizj.us/view/img/9924932/orthocarolina-dr-bruce-cohen*750xx1500-2000-0-84.jpg",
    "superHost": true,
    "verified": true,
    "listing_id": 62,
    "map": "don\"t forget to use a map",
    "locationDescription": "Where I live is located near the safari. It is a walking distance to the market and its near all the best view in Cape Town."
  },
  {
    "name": "Dominique Burns",
    "location": "Cape Town, South Africa",
    "join_date": "Joined in March 2010",
    "reviews": "590 Reviews",
    "references": "2 References",
    "description": "Living in Cape Town, South Africa, I am renting a beautiful clean and spacious room to anyone who wants to share the house with me. It is near the safari.",
    "languages": "Afrikaans, English, Xhosa and Zulu",
    "response_rate": "70%",
    "response_time": "within a few hours",
    "picture": "https://m.media-amazon.com/images/M/MV5BZmZkNTYzYjgtOTQyZS00MjRiLTlmZmItOTcyMTg0YmUwODRjXkEyXkFqcGdeQXVyMjIzOTc2ODk@._V1_UX214_CR0,0,214,317_AL_.jpg",
    "superHost": true,
    "verified": true,
    "listing_id": 63,
    "map": "don\"t forget to use a map",
    "locationDescription": "Cape Town is located in the beautiful side of South Africa. It is a walking distance to a Sinar View."
  },
  {
    "name": "Jovany Ford",
    "location": "Sao Paulo, Brazil",
    "join_date": "Joined in March 2011",
    "reviews": "538 Reviews",
    "references": "2 References",
    "description": "Living in Sao Paulo, Brazil, I love to take a walk. So glad to be able to use this opportunity to rent this house to those who wants to be my walking pair.",
    "languages": "Portuguese, English",
    "response_rate": "49%",
    "response_time": "within a few hours",
    "picture": "https://amp.businessinsider.com/images/5ad4c8f4146e7122008b49f1-750-563.jpg",
    "superHost": true,
    "verified": true,
    "listing_id": 64,
    "map": "don\"t forget to use a map",
    "locationDescription": "Jovany's home is located in Sao Paulo, Brazil."
  },
  {
    "name": "Harper Hendrix",
    "location": "Sao Paulo, Brazil",
    "join_date": "Joined in March 2012",
    "reviews": "500 Reviews",
    "references": "2 References",
    "description": "Living with a wife in this cute delightful fillhouse. Well it is at the heart of Seoul, the neighbourhood is peaceful that you won't be bothered by noises. It will be our pleasure if you find the same warmth as you feel at home.",
    "languages": "Portuguese, English",
    "response_rate": "90%",
    "response_time": "within a few hours",
    "picture": "https://images.summitmedia-digital.com/preview/images/articles/2016/04/15/korean/nm_korean.jpg",
    "superHost": true,
    "verified": true,
    "listing_id": 65,
    "map": "don\"t forget to use a map",
    "locationDescription": "Harper's home is located in Sao Paulo, Brazil."
  },
  {
    "name": "Armani York",
    "location": "Sao Paulo, Brazil",
    "join_date": "Joined in March 2011",
    "reviews": "430 Reviews",
    "references": "2 References",
    "description": "Born and raised in Italy, a realtor, a husband and a father of two sons. I am honored to be renting one of the properties in Seoul, South Korea.",
    "languages": "Portuguese, English",
    "response_rate": "90%",
    "response_time": "within a few hours",
    "picture": "http://www.italoamericano.org/sites/default/files/styles/crop_show/public/ricc.jpg?itok=po1TeEgQ",
    "superHost": true,
    "verified": true,
    "listing_id": 66,
    "map": "don\"t forget to use a map",
    "locationDescription": "Armani York's home is located in Sao Paulo, Brazil."
  },
  {
    "name": "Marth",
    "location": "New York City, NY",
    "join_date": "Joined in March 2011",
    "reviews": "568 Reviews",
    "references": "3 References",
    "description": "Born and raised from the Kingdom of Altea, and now living in New York with my sword and beautiful home. Happy to have the opportunity to share my home with people from around the world!",
    "languages": "English",
    "response_rate": "97%",
    "response_time": "within a few hours",
    "picture": "https://vignette.wikia.nocookie.net/fireemblem/images/4/45/Marth_Fates_Portrait.png/revision/latest?cb=20161015042604",
    "superHost": true,
    "verified": true,
    "listing_id": 67,
    "map": "don\"t forget to use a map",
    "locationDescription": "New York City is one of the best places where you can be, in New York. It is beautiful, nice, and wonderful."
  },{
    "name": "Mario",
    "location": "New York City, NY",
    "join_date": "Joined in March 2012",
    "reviews": "200 Reviews",
    "references": "2 References",
    "description": "Born and raised from Mushroom Kingdom, and now living in New York with my wife Peach and our pet Yoshi, who will leaving us soon. Happy to have the opportunity to share our homes with people from around the world!",
    "languages": "Italian, English",
    "response_rate": "93%",
    "response_time": "within an hour",
    "picture": "https://files.gamebanana.com/img/ss/srends/530-90_59bc49fd521ee.jpg",
    "superHost": true,
    "verified": true,
    "listing_id": 68,
    "map": "don\"t forget to use a map",
    "locationDescription": "Oh yeah, Petite Private Cottage is located in the safest area in New York. Beautiful, wonderful, and peaceful."
  },{
    "name": "Link",
    "location": "New York City, NY",
    "join_date": "Joined in March 2005",
    "reviews": "702 Reviews",
    "references": "4 References",
    "description": "Born and raised outside of Hyrule Temple, and now living in New York City with my wife Zelda and our son Young Link. We are happy to have the opportunity to share our homes with people from around the world!",
    "languages": "Elvish, English",
    "response_rate": "87%",
    "response_time": "within a few minutes",
    "picture": "https://www.ssbwiki.com/images/thumb/3/32/Link_SSB4.png/250px-Link_SSB4.png",
    "superHost": true,
    "verified": true,
    "listing_id": 69,
    "map": "don\"t forget to use a map",
    "locationDescription": "New York City is located in the most beautiful place on Earth you can ever find in New York City. It is an amazing and exciting city. There are numerous restaurants, bars, and people here!"
  },{
    "name": "Pikachu",
    "location": "Denver, CO",
    "join_date": "Joined in March 2014",
    "reviews": "50 Reviews",
    "references": "2 References",
    "description": "Born and raised in a lab from Pallet Town, and now living in Garden Suite in Denver Colorado. Happy to have the opportunity to share my park with people from around the world!",
    "languages": "Pokemanian",
    "response_rate": "89%",
    "response_time": "within a few hours",
    "picture": "https://www.ssbwiki.com/images/thumb/a/a0/Pikachu_SSB4.png/250px-Pikachu_SSB4.png",
    "superHost": true,
    "verified": true,
    "listing_id": 70,
    "map": "don\"t forget to use a map",
    "locationDescription": "Garden Suite is located in the Mission District and is an amazingly vibrant and exciting neighborhood. There are numerous restaurants, bars, and music options within two blocks of the house. This is a central location that offers quick access to the surrounding areas."
  },{
    "name": "Yoshi",
    "location": "Denver, CO",
    "join_date": "Joined in March 2012",
    "reviews": "345 Reviews",
    "references": "3 References",
    "description": "Born and raised from Yoshi Island, left Mario and family to have my own place. Happy to have the opportunity to share my home with people from around the world!",
    "languages": "Yoshinian",
    "response_rate": "40%",
    "response_time": "within a few hours",
    "picture": "https://www.ssbwiki.com/images/thumb/2/29/Yoshi_SSB4.png/250px-Yoshi_SSB4.png",
    "superHost": true,
    "verified": true,
    "listing_id": 71,
    "map": "don\"t forget to use a map",
    "locationDescription": "The neighborhood is a diverse and mixed use area. Western SOMA is considered a popular place for live-work environments and is the home to a lot of technology start-ups. There is access to public transportation, rental cars, buses, taxis, and bikes."
  },
  {
    "name": "Wario",
    "location": "Denver, CO",
    "join_date": "Joined in March 2016",
    "reviews": "145 Reviews",
    "references": "1 References",
    "description": "Born and raised from Mushroom Kingdom, left the gangsta's life and now living in Portland with the love of my life, my motorcycle.",
    "languages": "English",
    "response_rate": "10%",
    "response_time": "within a few hours",
    "picture": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRzHHEr8rWIbKjdcY91Ism9Tqngc9EUic63F3i2nICPhXilQoAO",
    "superHost": true,
    "verified": true,
    "listing_id": 72,
    "map": "don\"t forget to use a map",
    "locationDescription": "This efficiency studio is located in close-in SE Portland near tons of bars and restaurants. It's on the ground floor of a modern architecture townhouse offering the perfect location for exploring all things Portland! Sleep soundly in the hand-crafted queen murphy bed and walk to everything you need! Fully equipped kitchen and bathroom offers every convenience & the private patio is perfect for spring and summer days. The ductless heating and air-conditioner keeps you comfortable year-round!"
  },
  {
    "name": "Rosalina",
    "location": "Cleveland, OH",
    "join_date": "Joined in March 2014",
    "reviews": "545 Reviews",
    "references": "2 References",
    "description": "Born and raised from Gateway Galaxy, decided to move to Earth and settled in Cleveland in a cozy private loft apt. Happy to have the opportunity to share my apt with anyone, preferably a star.",
    "languages": "English",
    "response_rate": "90%",
    "response_time": "within a few hours",
    "picture": "https://www.mariowiki.com/images/thumb/6/6c/Rosalina_Artwork_-_Super_Mario_3D_World.png/200px-Rosalina_Artwork_-_Super_Mario_3D_World.png",
    "superHost": true,
    "verified": true,
    "listing_id": 73,
    "map": "don\"t forget to use a map",
    "locationDescription":  "Enjoy being at the heart of South Lake Union in downtown Cleveland, just steps from two Starbucks and several easy lunch spots, as well as a Tom Douglas restaurant and a fun sports bar. Explore further with the streetcar, just steps away."
  },
  {
    "name": "Donkey Kong",
    "location": "Cleveland, OH",
    "join_date": "Joined in March 2012",
    "reviews": "545 Reviews",
    "references": "2 References",
    "description": "Born and raised in a jungle, and now living in a New Capitol Hill Studio in Cleveland. Happy to rent my place to anyone who is a banana lover.",
    "languages": "English",
    "response_rate": "30%",
    "response_time": "within a few hours",
    "picture": "https://www.mariowiki.com/images/thumb/c/cb/Donkey_Kong_Artwork_%28alt%29_-_Donkey_Kong_Country_Tropical_Freeze.png/300px-Donkey_Kong_Artwork_%28alt%29_-_Donkey_Kong_Country_Tropical_Freeze.png",
    "superHost": true,
    "verified": true,
    "listing_id": 74,
    "map": "don\"t forget to use a map",
    "locationDescription": "Capitol Hill is known as the hip and vibrant neighborhood in Cleveland. You will bunch of nice restaurants, bars, and coffee shop especially around Pike and Pine St."
  },
  {
    "name": "Peach",
    "location": "Cleveland, OH",
    "join_date": "Joined in March 2013",
    "reviews": "500 Reviews",
    "references": "7 References",
    "description": "Born and raised in Mushroom Kingdom. I am a princess who left the kingdom because my husband wanted me to get away from whom he thought was my kidnapper. Truth is, just like hiding my relationship with Bowser from my husband, I do own a property in Cleveland, Ohio which has a free private room. It is cozy, beautiful, and warm!"
    ,
    "languages": "English",
    "response_rate": "80%",
    "response_time": "within a few hours",
    "picture": "https://pbs.twimg.com/profile_images/875781452163686400/RJ_erUsX_400x400.jpg",
    "superHost": true,
    "verified": true,
    "listing_id": 75,
    "map": "don\"t forget to use a map",
    "locationDescription": "I'm in Beacon Hill, an area conveniently located between SeaTac International Airport and downtown Cleveland. CenturyLink Field is less than 10 minutes away by car, if you're here for a concert or game."
  },
  {
    "name": "Browser",
    "location": "Miami, Florida",
    "join_date": "Joined in March 2011",
    "reviews": "329 Reviews",
    "references": "5 References",
    "description": "Living in Miami looking for Peach. In the meantime, check out this luxury downtown Getaway.",
    "languages": "English",
    "response_rate": "20%",
    "response_time": "within a few hours",
    "picture": "https://boygeniusreport.files.wordpress.com/2015/05/bowser_sm3dl.png?w=782",
    "superHost": true,
    "verified": true,
    "listing_id": 76,
    "map": "don\"t forget to use a map",
    "locationDescription": "Located in one of the most amazing areas of San Diego- To your West you are 6 blocks from The San Diego Bay, 3 blocks to the Village of Little Italy, To the East you are 6 blocks from the World Famous Balboa Park and Zoo. To the South you are 15 minutes from the Energetic Night Life of the Gaslamp District"
  },
  {
    "name": "Wal Luigi",
    "location": "Miami, Florida",
    "join_date": "Joined in March 2016",
    "reviews": "144 Reviews",
    "references": "4 References",
    "description": "All the way from Mushroom Kingdom, now living in Miami Florida. Got a spare room for anyone who loves to gamble and drink. Just 9 minutes away from the Strip.",
    "languages": "English",
    "response_rate": "30%",
    "response_time": "within a few hours",
    "picture": "http://images1.tickld.com/live/avatars/Waluigi_1546_avatar_20150323231235_e0c4e0aa65856031235ac6965ec14e4d.png",
    "superHost": true,
    "verified": true,
    "listing_id": 77,
    "map": "don\"t forget to use a map",
    "locationDescription": "Wal Luigi's Place is conveniently located near the strip (1.5 miles) and allows you to avoid the congestion to and from the airport. It's perfect for those looking for more chill surrounds while still being only a short Uber/taxi ride away from the strip. There is an Einstein Bros bagels and Starbucks within walking distance along with multiple inexpensive locally owned food options. There's a Go Kart Racing facility across the street called Pole Position Raceway."
  },
  {
    "name": "King Dedede",
    "location": "Miami, Florida",
    "join_date": "Joined in March 2016",
    "reviews": "700 Reviews",
    "references": "3 References",
    "description": "Living Miami Florida, looking for anyone who is cool enough to share a space with the King himself.",
    "languages": "English",
    "response_rate": "40%",
    "response_time": "within a few hours",
    "picture": "https://vignette.wikia.nocookie.net/deathbattlefanon/images/4/4d/Kingdedede.png/revision/latest?cb=20140809054519",
    "superHost": true,
    "verified": true,
    "listing_id": 78,
    "map": "don\"t forget to use a map",
    "locationDescription": "King Dedede's home is located in Miami Florida, United States. There is a city bus stop located just across the street from my space and also Grid bicycle rentals on the North West corner of 5th ave."
  },
  {
    "name": "Toad",
    "location": "Virginia Beach, Virginia",
    "join_date": "Joined in March 2011",
    "reviews": "800 Reviews",
    "references": "2 References",
    "description": "Born and raised in Mushroom Kingdom. Now living in Virginia where everything is greener and humid. Renting out the beautiful Bohemian Pool House to anyone who wants to have fun!",
    "languages": "English, Toadian",
    "response_rate": "90%",
    "response_time": "within a few hours",
    "picture": "https://vignette.wikia.nocookie.net/scratchpad/images/1/19/Toad.jpg/revision/latest?cb=20121202001316",
    "superHost": true,
    "verified": true,
    "listing_id": 79,
    "map": "don\"t forget to use a map",
    "locationDescription": "Toad’s home is located in Virginia. Within 5-10 min walk you have the following places: Shopping Mall, Hilton, Japanese restaurants, Sky Bar, Multiple restaurants, Starbucks."
  },
  {
    "name": "Kirby",
    "location": "Virginia Beach, Virginia",
    "join_date": "Joined in March 2010",
    "reviews": "1001 Reviews",
    "references": "5 References",
    "description": "Born and raised in Dream Land, migrated to Virginia and bought a beautiful property near Pacifico. Looking for anyone who wants to play with me!",
    "languages": "English, Japanese",
    "response_rate": "90%",
    "response_time": "within a few hours",
    "picture": "https://upload.wikimedia.org/wikipedia/en/thumb/5/5c/Kirby.png/220px-Kirby.png",
    "superHost": true,
    "verified": true,
    "listing_id": 80,
    "map": "don\"t forget to use a map",
    "locationDescription": "Kirby's home is located in Virginia Beach, Virginia."
  },
  {
    "name": "Jon Snow",
    "location": "Virginia Beach, Virginia",
    "join_date": "Joined in March 2011",
    "reviews": "340 Reviews",
    "references": "2 References",
    "description": "Born and raised in Winterfell, now living in Saudi Arabia, away from the snow. Happy to have the opportunity to share my suite with anyone!",
    "languages": "English",
    "response_rate": "50%",
    "response_time": "within a few hours",
    "picture": "https://pbs.twimg.com/profile_images/901947348699545601/hqRMHITj_400x400.jpg",
    "superHost": true,
    "verified": true,
    "listing_id": 81,
    "map": "don\"t forget to use a map",
    "locationDescription": "Jon Snow's home is located in Jeddah, Makkah Province, Saudi Arabia."
  },
  {
    "name": "Daenerys Targaryen",
    "location": "Cincinnati, VA",
    "join_date": "Joined in March 2011",
    "reviews": "580 Reviews",
    "references": "5 References",
    "description": "Tired of the Iron Throne, I retire myself in Cincinnati. Now living in Green Garden room, I welcome anyone who wants to rent the space. Don't worry, my dragons won't bite you, if you behave yourself.",
    "languages": "English",
    "response_rate": "100%",
    "response_time": "within a few minutes",
    "picture": "https://i.ytimg.com/vi/WtXo__olwu8/maxresdefault.jpg",
    "superHost": true,
    "verified": true,
    "listing_id": 82,
    "map": "don\"t forget to use a map",
    "locationDescription": "Daenerys Targaryen’s home is located in Cincinnati, VA."
  },
  {
    "name": "Tyrian Lannister",
    "location": "Cincinnati, VA",
    "join_date": "Joined in March 2012",
    "reviews": "510 Reviews",
    "references": "2 References",
    "description": "Followed Daenerys all the way to Cincinnati, VA, I now live by myself in a luxury house all to myself. Feeling lonely, renting out a luxury room for anyone who wants to keep me accompany.",
    "languages": "English",
    "response_rate": "98%",
    "response_time": "within a few minutes",
    "picture": "https://img.resized.co/buzz_ie/eyJkYXRhIjoie1widXJsXCI6XCJodHRwOlxcXC9cXFwvczMtZXUtd2VzdC0xLmFtYXpvbmF3cy5jb21cXFwvc3RvcmFnZS5wdWJsaXNoZXJwbHVzLmllXFxcL21lZGlhLmJ1enouaWVcXFwvdXBsb2Fkc1xcXC8yMDE3XFxcLzA0XFxcL3R5cmlvbi1sYW5uaXN0ZXItbGF1Z2hpbmctZ2FtZS1vZi10aHJvbmVzLS0xMDI0eDUzOS5wbmdcIixcIndpZHRoXCI6NzAwLFwiaGVpZ2h0XCI6MzcwLFwiZGVmYXVsdFwiOlwiaHR0cHM6XFxcL1xcXC93d3cuYnV6ei5pZVxcXC9pXFxcL25vLWltYWdlLnBuZ1wifSIsImhhc2giOiI4MTk0MGJiYThmZWFkNWVhZmUxZmNkMzNiYzk3NzYwYjc1NWE4NWQyIn0=/tyrion-lannister-laughing-game-of-thrones-1024x539.png",
    "superHost": true,
    "verified": true,
    "listing_id": 83,
    "map": "don\"t forget to use a map",
    "locationDescription": "Tyrian's home is located in Cincinnati, VA. Affluent neighbourhood with plenty of parks. The 400-acre Hauz Khas forest is a 5-min walk away. Extremely safe with 24-hr guard patrols. Small market within 2 mins walking distance for all essentials - groceries, milk, medicines, dry clean service, ATM, phone recharge. You're 2 mins away from the neighbourhood health club where you can use the gym/swimming pool/massage facilities/spa"
  },
  {
    "name": "Bronn",
    "location": "Cincinnati, VA",
    "join_date": "Joined in March 2014",
    "reviews": "280 Reviews",
    "references": "3 References",
    "description": "Away from the war of the Iron Throne, I am now living in Cincinnati VA in a beautiful colorful house. One beautiful blue bedroom is available for anyone who wants to share the space with me.",
    "languages": "English",
    "response_rate": "70%",
    "response_time": "within a few hours",
    "picture": "https://www.hbo.com/content/dam/hbodata/series/game-of-thrones/character/s5/bronn-1920.jpg/_jcr_content/renditions/cq5dam.web.1200.675.jpeg",
    "superHost": true,
    "verified": true,
    "listing_id": 84,
    "map": "don\"t forget to use a map",
    "locationDescription": "The neighborhood is very peaceful in spite of being close to the city centre. In 3 minutes you are at a big supermarket, and you are in walking distance to good restaurants and the best coffee shops."
  },
  {
    "name": "Joffrey",
    "location": "Busan, South Korea",
    "join_date": "Joined in March 2012",
    "reviews": "3 Reviews",
    "references": "2 References",
    "description": "They think I am dead. Well well, surprise, I am well and alive. Recovering for years in a hospital in South Korea, I now decided to stay and bought myself a beautiful place. Renting a loft with 2 beds with beautiful view in Busan.",
    "languages": "English",
    "response_rate": "10%",
    "response_time": "within a few hours",
    "picture": "https://vignette.wikia.nocookie.net/gameofthrones/images/4/4d/Purple_Wedding.png/revision/latest?cb=20150210223603",
    "superHost": true,
    "verified": true,
    "listing_id": 85,
    "map": "don\"t forget to use a map",
    "locationDescription": "The neighborhood is at the centre of Busan's Former French Concession & in walking distance from 4 subway lines(Line 1, 7, 9 & 10). Also, it is located near the Hengshan Road bars & pubs, popular cafes & restaurants, cinemas, visitor attractions."
  },
  {
    "name": "Iggrid",
    "location": "Busan, South Korea",
    "join_date": "Joined in March 2014",
    "reviews": "194 Reviews",
    "references": "5 References",
    "description": "I was once declared dead. But the Lord of Light resurrected me and one day I woke up in South Korea. Don't know how to go back to my home with the Wildlings. But I like it here and bought myself an apartment to myself. Anyways, anyone wants to share the space with me, here's your opportunity!",
    "languages": "English",
    "response_rate": "80%",
    "response_time": "within a few minutes",
    "picture": "https://vignette.wikia.nocookie.net/gameofthrones/images/2/28/Ygritte-promotionals4pic.jpg/revision/latest?cb=20170107042949",
    "superHost": true,
    "verified": true,
    "listing_id": 86,
    "map": "don\"t forget to use a map",
    "locationDescription": "Iggrid’s home is located in Busan, South Korea."
  },
  {
    "name": "Theon Greyjoy",
    "location": "Busan, South Korea",
    "join_date": "Joined in March 2015",
    "reviews": "90 Reviews",
    "references": "2 References",
    "description": "My name is Theon, Theon Greyjoy. I'm renting out an awesome getaway spot in Korea for those who wants to relax here in Busan, South Korea",
    "languages": "English",
    "response_rate": "40%",
    "response_time": "within a few hours",
    "picture": "https://cdn-images-1.medium.com/max/1600/1*-gDptk0nn2dGpMCx3K9Ftw.jpeg",
    "superHost": true,
    "verified": true,
    "listing_id": 87,
    "map": "don\"t forget to use a map",
    "locationDescription": "This is the best spot in South Korea. Everything happens here. All big events are just 1 min. to walk away. Any kind of parade or concert (like the Stones) will either be on the beach in front of Copacabana Palace Hotel or on Avenida Atlantica. It's definitely the most lively area in all of Busan. - The apt is very spacious. Everyone adores the huge balcony (on second floor) which allows you to see the action below. There are no cars passing. It's a pedestrian street, and you will see Brazilians socializing, having a churrasco, playing a guitar, dancing etc. - The subway station Cardeal Arco Verde and all major bus lines are a short walk away, so it's extremely easy to move around. Most people stay put, though, since you're at the best spot anyway!"
  },
  {
    "name": "Samuell Tarly",
    "location": "Tokyo, Japan",
    "join_date": "Joined in March 2013",
    "reviews": "230 Reviews",
    "references": "4 References",
    "description": "Coming all the way down here by myself to Japan to study their new modern medicines. Looking for anyone who is willing to be my assistant in this Roomy Apartment near Downtown.",
    "languages": "English",
    "response_rate": "90%",
    "response_time": "within a few minutes",
    "picture": "http://www.wetpaint.com/wp-content/uploads/2017/03/game-of-thrones-samwell-tarly-750x522-1489000496.jpg",
    "superHost": true,
    "verified": true,
    "listing_id": 88,
    "map": "don\"t forget to use a map",
    "locationDescription": "The neighborhood is a trendy, safe and green area of the city. Bikes routes, walking roads, as well as two parks are available around, with lots of great restaurants and places to enjoy the nightlife. The area is secure, going out and walking home is safe even during the night."
  },
  {
    "name": "Hodor",
    "location": "Tokyo, Japan",
    "join_date": "Joined in March 2013",
    "reviews": "300 Reviews",
    "references": "3 References",
    "description": "Although all I can say is Hodor. What I meant to say is that I will hold the door for anyone who wants to adventure themselves in a European Style Apartment close to Mizuki Mall here in Tokyo, Japan.",
    "languages": "Hodor",
    "response_rate": "98%",
    "response_time": "within a few minutes",
    "picture": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/avatars/70/7035ffad65de2bc1c0d08c24aaf9bb57f7130be6_full.jpg",
    "superHost": true,
    "verified": true,
    "listing_id": 89,
    "map": "don\"t forget to use a map",
    "locationDescription": "The neighborhood is at the centre of Tokyo's Former French Concession & in walking distance from 4 subway lines(Line 1, 7, 9 & 10). Also, it is located near the Hengshan Road bars & pubs, popular cafes & restaurants, cinemas, visitor attractions."
  },
  {
    "name": "Sansa Stark",
    "location": "Tokyo, Japan",
    "join_date": "Joined in March 2013",
    "reviews": "500 Reviews",
    "references": "2 References",
    "description": "Having to go through a bunch of horrible experiences, I decided to move myself to Tokyo in Japan. Living in a modern flat in Tokyo, I welcome anyone who wants share the space with me. Preferably a girl.",
    "languages": "English",
    "response_rate": "98%",
    "response_time": "within a few minutes",
    "picture": "https://pbs.twimg.com/profile_images/567089182615830528/F2H311Ev_400x400.jpeg",
    "superHost": true,
    "verified": true,
    "listing_id": 90,
    "map": "don\"t forget to use a map",
    "locationDescription": "If you want to enjoy the most genuine and authentic Tokyo's Heart, while being hosted in a very quiet and silent apartment in one the most typical districts of the whole city, and at the same time discovering the most multicultural, bohemian and alternative neighborhood in Tokyo, just a few minutes walking from all the main highlights and touristics spots of the city, my apartment at Lavapiés is the perfect place for you. My apartment will be the perfect place for you to enjoy a romantic scape with your partner, a fantastic stay with a friend and also a great family gateway to discover the beauty and magic of Tokyo!!"
  },
  {
    "name": "Tywin Lannister",
    "location": "Dubai, United Arab Emirates",
    "join_date": "Joined in March 2012",
    "reviews": "576 Reviews",
    "references": "2 References",
    "description": "They thought that I was dead. Well well, my son has failed to kill me. I faked my own death in hope of the Lannister step up their game and take over the Iron Throne. I migrated myself in Dubai and renting properties. Welcome to the perfect spot with views of the Jozi sunset.",
    "languages": "English",
    "response_rate": "70%",
    "response_time": "within a few minutes",
    "picture": "https://www.themarysue.com/wp-content/uploads/2014/09/tywin.jpg",
    "superHost": true,
    "verified": true,
    "listing_id": 91,
    "map": "don\"t forget to use a map",
    "locationDescription": "Tywin Lannister's palace is in Dubai, United Arab Emirates"
  },
  {
    "name": "Annalise Valdez",
    "location": "Dubai, United Arab Emirates",
    "join_date": "Joined in March 2012",
    "reviews": "578 Reviews",
    "references": "2 References",
    "description": "Born and raised in Dubai, a real estate agent. I have the opportunity to welcome anyone to this beautiful house with a balcony and city view.",
    "languages": "Hindi, English, Dubai",
    "response_rate": "70%",
    "response_time": "within a few minutes",
    "picture": "https://s3-media3.fl.yelpcdn.com/bphoto/aQIAfFc8pK7rN47LA8w8tg/ls.jpg",
    "superHost": true,
    "verified": true,
    "listing_id": 92,
    "map": "don\"t forget to use a map",
    "locationDescription": "Annalise's home is located in Dubai, United Arab Emirates"
  },
  {
    "name": "Itzel Blanchard",
    "location": "Dubai, United Arab Emirates",
    "join_date": "Joined in March 2011",
    "reviews": "600 Reviews",
    "references": "3 References",
    "description": "Born and raised in Dubai, United Arab Emirates, and now honored to have the opportunity to share my home with people from around the world!",
    "languages": "English, Hindi",
    "response_rate": "97%",
    "response_time": "within a few hours",
    "picture": "https://i.pinimg.com/236x/52/c4/e9/52c4e9e859d7f55cb83c65d10c1560e6--noroc-cali-colombia.jpg",
    "superHost": true,
    "verified": true,
    "listing_id": 93,
    "map": "don\"t forget to use a map",
    "locationDescription": "Itzel Blanchard's home is located in Dubai, United Arab Emirates."
  },
  {
    "name": "Julie Gray",
    "location": "Kansas City, MO",
    "join_date": "Joined in March 2007",
    "reviews": "903 Reviews",
    "references": "4 References",
    "description": "The name is Gray, Julie Gray. Two dogs. Animal lovers. Design lover. Which brings me the opportunity to share a brand nw house with amazing views and location to anyone who appreciates beauty!",
    "languages": "English",
    "response_rate": "97%",
    "response_time": "within a few hours",
    "picture": "http://members.openbooktoronto.com/sites/default/files/obt/illustrations/profile%20pic.jpg",
    "superHost": true,
    "verified": true,
    "listing_id": 94,
    "map": "don\"t forget to use a map",
    "locationDescription": "Julie's home is located in Kansas City, MO."
  },
  {
    "name": "Cohen Lowe",
    "location": "Kansas City, MO",
    "join_date": "Joined in March 2011",
    "reviews": "589 Reviews",
    "references": "2 References",
    "description": "Born and raised in Los Angeles, now living in Kansas City, MO. I have the opportunity to rent one of my modern and comfy flat with super location to anyone who wants to have a relaxing time!",
    "languages": "English",
    "response_rate": "68%",
    "response_time": "within a few hours",
    "picture": "http://media.bizj.us/view/img/9924932/orthocarolina-dr-bruce-cohen*750xx1500-2000-0-84.jpg",
    "superHost": true,
    "verified": true,
    "listing_id": 95,
    "map": "don\"t forget to use a map",
    "locationDescription": "Where I live is located near Kansas City, MO. It is a walking distance to the mall and its near all the best restaurants in Kansas City."
  },
  {
    "name": "Dominique Burns",
    "location": "Ho Chi Minh City, Vietnam",
    "join_date": "Joined in March 2010",
    "reviews": "590 Reviews",
    "references": "2 References",
    "description": "Living in Ho Chi Minh City, Vietnam, I am renting a beautiful clean and spacious room to anyone who wants to share the house with me. It is near the mall.",
    "languages": "English, Vienamese",
    "response_rate": "70%",
    "response_time": "within a few hours",
    "picture": "https://m.media-amazon.com/images/M/MV5BZmZkNTYzYjgtOTQyZS00MjRiLTlmZmItOTcyMTg0YmUwODRjXkEyXkFqcGdeQXVyMjIzOTc2ODk@._V1_UX214_CR0,0,214,317_AL_.jpg",
    "superHost": true,
    "verified": true,
    "listing_id": 96,
    "map": "don\"t forget to use a map",
    "locationDescription": "Darmo Harpan is located in the beautiful side of Surabaya. It is a walking distance to a Sinar Mall."
  },
  {
    "name": "Jovany Ford",
    "location": "Phuket City, Thailand",
    "join_date": "Joined in March 2011",
    "reviews": "538 Reviews",
    "references": "2 References",
    "description": "Living in Phuket City, Thailand, I love to take a walk. So glad to be able to use this opportunity to rent this house to those who wants to be my walking pair.",
    "languages": "English, Thai",
    "response_rate": "49%",
    "response_time": "within a few hours",
    "picture": "https://amp.businessinsider.com/images/5ad4c8f4146e7122008b49f1-750-563.jpg",
    "superHost": true,
    "verified": true,
    "listing_id": 97,
    "map": "don\"t forget to use a map",
    "locationDescription": "Jovany's home is located in Seoul, Phuket City, Thailand"
  },
  {
    "name": "Harper Hendrix",
    "location": "Phuket City, Thailand",
    "join_date": "Joined in March 2012",
    "reviews": "500 Reviews",
    "references": "2 References",
    "description": "Living with a wife in this cute delightful fillhouse. Well it is at the heart of Seoul, the neighbourhood is peaceful that you won't be bothered by noises. It will be our pleasure if you find the same warmth as you feel at home.",
    "languages": "English, Thai",
    "response_rate": "90%",
    "response_time": "within a few hours",
    "picture": "https://images.summitmedia-digital.com/preview/images/articles/2016/04/15/korean/nm_korean.jpg",
    "superHost": true,
    "verified": true,
    "listing_id": 98,
    "map": "don\"t forget to use a map",
    "locationDescription": "Harper's home is located in Phuket City, Thailand."
  },
  {
    "name": "Armani York",
    "location": "Phuket City, Thailand",
    "join_date": "Joined in March 2011",
    "reviews": "430 Reviews",
    "references": "2 References",
    "description": "Born and raised in Italy, a realtor, a husband and a father of two sons. I am honored to be renting one of the properties in Phuket City, Thailand.",
    "languages": "English, Thai",
    "response_rate": "90%",
    "response_time": "within a few hours",
    "picture": "http://www.italoamericano.org/sites/default/files/styles/crop_show/public/ricc.jpg?itok=po1TeEgQ",
    "superHost": true,
    "verified": true,
    "listing_id": 99,
    "map": "don\"t forget to use a map",
    "locationDescription": "Jovany lives in Phuket City, Thailand."
  },
  {
    "name": "Marth",
    "location": "Phuket City, Thailand",
    "join_date": "Joined in March 2011",
    "reviews": "568 Reviews",
    "references": "3 References",
    "description": "Born and raised from the Kingdom of Altea, and now living in Phuket City, Thailand with my sword and beautiful home. Happy to have the opportunity to share my home with people from around the world!",
    "languages": "English",
    "response_rate": "97%",
    "response_time": "within a few hours",
    "picture": "https://vignette.wikia.nocookie.net/fireemblem/images/4/45/Marth_Fates_Portrait.png/revision/latest?cb=20161015042604",
    "superHost": true,
    "verified": true,
    "listing_id": 100,
    "map": "don\"t forget to use a map",
    "locationDescription": "Phuket City, Thailand is one of the best places where you can be in. It is beautiful, nice, and kingdomy."
  }
]

module.exports = {
  seeds: seeds
};